// <auto-generated />
using System;
using Finance_Manager_Icarus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finance_Manager_Icarus.Migrations
{
    [DbContext(typeof(FinanceManagerIcarusContext))]
    [Migration("20250503192253_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Finance_Manager_Icarus.Models.Banco", b =>
                {
                    b.Property<Guid>("Banco_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Usuario_Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("data_atualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("data_criacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("data_exclusao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Banco_Id");

                    b.HasIndex("Usuario_Id");

                    b.ToTable("banco");
                });

            modelBuilder.Entity("Finance_Manager_Icarus.Models.Cartao", b =>
                {
                    b.Property<Guid>("Cartao_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Banco_Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("data_atualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("data_criacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("data_exclusao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Cartao_Id");

                    b.HasIndex("Banco_Id");

                    b.ToTable("cartao");
                });

            modelBuilder.Entity("Finance_Manager_Icarus.Models.Categoria", b =>
                {
                    b.Property<Guid>("Categoria_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Usuario_Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("data_atualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("data_criacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("data_exclusao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Categoria_Id");

                    b.HasIndex("Usuario_Id");

                    b.ToTable("categoria");
                });

            modelBuilder.Entity("Finance_Manager_Icarus.Models.Movimentacao", b =>
                {
                    b.Property<Guid>("Movimentacao_Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Banco_Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Cartao_Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<bool>("Entrada")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("NomeMovimentacao_Id")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("data_atualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("data_criacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("data_exclusao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Movimentacao_Id");

                    b.HasIndex("Banco_Id");

                    b.HasIndex("Cartao_Id");

                    b.ToTable("movimentacao");
                });

            modelBuilder.Entity("Finance_Manager_Icarus.Models.NomeMovimentacao", b =>
                {
                    b.Property<Guid>("Nome_movimentacao_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Categoria_Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Usuario_Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("data_atualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("data_criacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("data_exclusao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Nome_movimentacao_id");

                    b.HasIndex("Categoria_Id");

                    b.HasIndex("Usuario_Id");

                    b.ToTable("nome_movimentacao");
                });

            modelBuilder.Entity("Finance_Manager_Icarus.Models.Usuario", b =>
                {
                    b.Property<Guid>("Usuario_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("data_atualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("data_criacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("data_exclusao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Usuario_Id");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("Finance_Manager_Icarus.Models.Banco", b =>
                {
                    b.HasOne("Finance_Manager_Icarus.Models.Usuario", "Usuario")
                        .WithMany("Bancos")
                        .HasForeignKey("Usuario_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Finance_Manager_Icarus.Models.Cartao", b =>
                {
                    b.HasOne("Finance_Manager_Icarus.Models.Banco", "Banco")
                        .WithMany("Cartoes")
                        .HasForeignKey("Banco_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banco");
                });

            modelBuilder.Entity("Finance_Manager_Icarus.Models.Categoria", b =>
                {
                    b.HasOne("Finance_Manager_Icarus.Models.Usuario", "Usuario")
                        .WithMany("Categorias")
                        .HasForeignKey("Usuario_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Finance_Manager_Icarus.Models.Movimentacao", b =>
                {
                    b.HasOne("Finance_Manager_Icarus.Models.Banco", "Banco")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("Banco_Id");

                    b.HasOne("Finance_Manager_Icarus.Models.Cartao", "Cartao")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("Cartao_Id");

                    b.HasOne("Finance_Manager_Icarus.Models.NomeMovimentacao", "NomeMovimentacao")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("Movimentacao_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banco");

                    b.Navigation("Cartao");

                    b.Navigation("NomeMovimentacao");
                });

            modelBuilder.Entity("Finance_Manager_Icarus.Models.NomeMovimentacao", b =>
                {
                    b.HasOne("Finance_Manager_Icarus.Models.Categoria", "Categoria")
                        .WithMany("NomeMovimentacoes")
                        .HasForeignKey("Categoria_Id");

                    b.HasOne("Finance_Manager_Icarus.Models.Usuario", "Usuario")
                        .WithMany("NomeMovimentacoes")
                        .HasForeignKey("Usuario_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Finance_Manager_Icarus.Models.Banco", b =>
                {
                    b.Navigation("Cartoes");

                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("Finance_Manager_Icarus.Models.Cartao", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("Finance_Manager_Icarus.Models.Categoria", b =>
                {
                    b.Navigation("NomeMovimentacoes");
                });

            modelBuilder.Entity("Finance_Manager_Icarus.Models.NomeMovimentacao", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("Finance_Manager_Icarus.Models.Usuario", b =>
                {
                    b.Navigation("Bancos");

                    b.Navigation("Categorias");

                    b.Navigation("NomeMovimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
